import Home from "../pages/home";
import type { AppProps } from "next/app";
import Head from "next/head";

export default function App({ Component, pageProps }: AppProps) {
  return <>
    <Head>
      <title>Easy Next.js + Tailwind CSS Dropdown Menus</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
      <script src="https://cdn.tailwindcss.com"></script>
    </Head>
    <Home/>
  </>
}